In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

import pandas as pd
import numpy as np

from expenses.data import *
from expenses.tables import *
from expenses.utils import ROOT_DIR
from expenses.db import *
from expenses.categories import *
from expenses.analyse import Analysis

In [3]:
ROOT_DIR

PosixPath('/home/micha/python_projects/expenses')

In [3]:
a = Analysis()
d = a.data_
c = a.cat

could not read T_DATA from DB: Execution failed on sql 'SELECT data.id, data.date, data.execution_date, data.title, data.vendor, data.account, data.amount, data.balance, data.category, data.sub_category
FROM data': (sqlite3.OperationalError) no such table: data
[SQL: SELECT data.id, data.date, data.execution_date, data.title, data.vendor, data.account, data.amount, data.balance, data.category, data.sub_category
FROM data]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

OperationalError: (sqlite3.OperationalError) no such table: file_hashes
[SQL: SELECT file_hashes.fname AS file_hashes_fname, file_hashes.hash AS file_hashes_hash, file_hashes.time_stamp AS file_hashes_time_stamp
FROM file_hashes
WHERE file_hashes.fname = ?]
[parameters: ('/home/micha/python_projects/expenses/data/categories.json',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [4]:
# dummy

In [33]:
a.plot_category('Transportation', show_month=0)

In [30]:
d.groupby('category').amount.sum().sort_values(ascending=False)

category
Income                     293376.62
Insurance                    -634.00
Miscellaneous               -4041.00
Entertainment & Leisure    -11811.75
Exclude                    -27456.17
Personal & Family Care     -42960.62
Housing                    -45229.35
Food & Groceries           -52491.95
Transportation             -77590.61
Name: amount, dtype: float64

In [28]:
d.category.value_counts()

category
Food & Groceries           1220
Personal & Family Care      415
Transportation              187
Exclude                     125
Housing                     120
Income                      116
Entertainment & Leisure     111
Miscellaneous                 8
Insurance                     1
Name: count, dtype: int64

In [ ]:
a.show_date(2024, 11)

In [101]:
d.query('title.str.contains("and bied", case=False, na=False)')

,date,execution_date,title,vendor,account,amount,balance,category,sub_category
id,,,,,,,,,
1016,2024-05-15,2024-05-15,from Vova May after taxes and biedronka,IULIIA MISHCHENKO UL. AL. LIPOWA 22/9 53-124 W...,07 1090 2402 0000 0001 2393 8242,2050.0,2213.15,None,None

In [29]:
a.show_uncategorised(10)

In [16]:
x = d.uncategorised

In [18]:
x[x.amount == -305.41]

,date,execution_date,title,vendor,account,amount,balance
id,,,,,,,
299,2023-07-10,2023-07-10,Zakup BLIK Blue Media S.A. Powstancow Warszawy...,Blue Media S.A. Powstancow Warszawy 681-718 Sopot,72 1090 1489 0000 0000 4800 3393,-305.41,796.85

## Categories


1. Housing

- Rent/Mortgage
- Property Taxes
- Home Insurance
- Maintenance/Repairs
- Utilities (Electricity, Water, Gas)

2. Transportation
- Car Payments/Leasing
- Fuel
- Insurance
- Public Transportation
- Maintenance and Repairs
- Parking Fees/Tolls

3. Food & Groceries
- Groceries
- Dining Out
- Coffee/Snacks
- Meal Delivery Services

4. Health & Wellness

Health Insurance
Medical Bills (Doctor, Dentist, etc.)
Medications
Fitness (Gym Memberships, Classes)
Personal Care (Haircuts, Skincare)

5. Entertainment & Leisure

Streaming Subscriptions
Movies, Concerts, Events
Books, Magazines
Hobbies (Music, Crafts, etc.)
Travel/Vacations

6. Personal & Family Care

Childcare/Schooling
Pet Care (Food, Vet)
Clothing & Accessories
Gifts & Special Occasions

7. Insurance

Life Insurance
Disability Insurance
Home/Renters Insurance
Vehicle Insurance

8. Debt Repayment

Credit Card Payments
Student Loans
Personal Loans
Mortgage

9. Savings & Investments

Emergency Fund
Retirement Contributions
Stocks/Mutual Funds
Savings Accounts

10. Miscellaneous

Donations/Charity
Professional Services (Legal, Accounting)
Miscellaneous Fees/Bank Fees
Unexpected/One-time Expenses

## Data

In [16]:
for i in d[d.vendor.str.contains('PLUS BANK SA').fillna(False)].sort_values('date').iloc[-4:].title:
    print(i)

Zakup BLIK PLUS BANK SA Al. Stanow Zjednoczonych 6104-028 Warszawa ref:88260281624
Zakup BLIK PLUS BANK SA Al. Stanow Zjednoczonych 6104-028 Warszawa ref:88909240509
Zakup BLIK PLUS BANK SA Al. Stanow Zjednoczonych 6104-028 Warszawa ref:89627324696
Zakup BLIK PLUS BANK SA Al. Stanow Zjednoczonych 6104-028 Warszawa ref:90201380767

/tmp/ipykernel_21166/3238185134.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  for i in d[d.vendor.str.contains('PLUS BANK SA').fillna(False)].sort_values('date').iloc[-4:].title: